/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:dc238e61-f9bc-45a6-83ca-e6e4533d73d8",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_qGTCdfWR9",
    "aws_user_pools_web_client_id": "1chvihv9thllnrpbvh8a3ks3ik",
    "oauth": {}
};


export default awsmobile;
